export const keyCodeToLabel = new Map([
  ["Digit1", "1"],
  ["Digit2", "2"],
  ["Digit3", "3"],
  ["Digit4", "4"],
  ["Digit5", "5"],
  ["Digit6", "6"],
  ["Digit7", "7"],
  ["Digit8", "8"],
  ["Digit9", "9"],
  ["Digit0", "0"],
  ["Minus", "-"],
  ["Equal", "="],

  ["KeyQ", "q"],
  ["KeyW", "w"],
  ["KeyE", "e"],
  ["KeyR", "r"],
  ["KeyT", "t"],
  ["KeyY", "y"],
  ["KeyU", "u"],
  ["KeyI", "i"],
  ["KeyO", "o"],
  ["KeyP", "p"],
  ["BracketLeft", "["],
  ["BracketRight", "]"],

  ["KeyA", "a"],
  ["KeyS", "s"],
  ["KeyD", "d"],
  ["KeyF", "f"],
  ["KeyG", "g"],
  ["KeyH", "h"],
  ["KeyJ", "j"],
  ["KeyK", "k"],
  ["KeyL", "l"],
  ["Semicolon", ";"],
  ["Quote", "'"],

  ["KeyZ", "z"],
  ["KeyX", "x"],
  ["KeyC", "c"],
  ["KeyV", "v"],
  ["KeyB", "b"],
  ["KeyN", "n"],
  ["KeyM", "m"],
  ["Comma", ","],
  ["Period", "."],
  ["Slash", "/"],
])

export const keyboardRows = [
  [
    "Digit1",
    "Digit2",
    "Digit3",
    "Digit4",
    "Digit5",
    "Digit6",
    "Digit7",
    "Digit8",
    "Digit9",
    "Digit0",
    "Minus",
    "Equal",
  ],
  [
    "KeyQ",
    "KeyW",
    "KeyE",
    "KeyR",
    "KeyT",
    "KeyY",
    "KeyU",
    "KeyI",
    "KeyO",
    "KeyP",
    "BracketLeft",
    "BracketRight",
  ],
  [
    "KeyA",
    "KeyS",
    "KeyD",
    "KeyF",
    "KeyG",
    "KeyH",
    "KeyJ",
    "KeyK",
    "KeyL",
    "Semicolon",
    "Quote",
  ],
  [
    "KeyZ",
    "KeyX",
    "KeyC",
    "KeyV",
    "KeyB",
    "KeyN",
    "KeyM",
    "Comma",
    "Period",
    "Slash",
  ],
]
